language: java

jdk:
  - openjdk8
  - oraclejdk8

branches:
  only:
  - master

sudo: required

before_install:
  - sudo apt update

install:
  - sudo apt install maven -y # this command is only for demonstration reason. Any Travis virtual machine has maven pre-installed by default.

before_script: 
  - cd project  # enter Maven root directory
  - ls -la

script: 
  - mvn clean package jacoco:report coveralls:report # the coveralls:report is required only for the coveralls coverage service 

after_success:
- bash <(curl -s https://codecov.io/bash) -t 1036eb64-2d96-44c6-b132-0dde4e7dfcca # replace the 1036eb64-2d96-44c6-b132-0dde4e7dfcca with your repository's token obtained by CodeCov
